steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/springboot-example', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/springboot-example']
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=/kubernetesfile.yaml
      - --image=gcr.io/$PROJECT_ID/springboot-example:latest
      - --location=europe-west1-b
      - --cluster=cluster-1
images:
  - 'gcr.io/$PROJECT_ID/springboot-example'