steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
    id: Test
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['install','-Dmaven.test.skip=true']
    id: Install
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '.']
    id: Build
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
    id: Push
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=${_K8S_YAML_PATH}
      - --image=${_IMAGE_NAME}:latest
      - --location=${_GKE_LOCATION}
      - --cluster=${_GKE_CLUSTER}
    id: Deploy
images:
  - 'gcr.io/$PROJECT_ID/springboot-example'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_YAML_PATH: kubernetesfile.yaml
  _IMAGE_NAME: gcr.io/eternal-trainer-271923/springboot-example
  _GKE_LOCATION: europe-west6-a
  _GKE_CLUSTER: cluster-1