apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2020-07-13T06:00:58Z","generation":5,"labels":{"app":"spring-boot-test","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy"},"name":"spring-boot-test","namespace":"default","resourceVersion":"2666850","selfLink":"/apis/apps/v1/namespaces/default/deployments/spring-boot-test","uid":"1953c04e-003c-4e18-80a0-a7798d5d9e87"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"spring-boot-test"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"spring-boot-test","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy"}},"spec":{"containers":[{"image":"gcr.io/eternal-trainer-271923/springboot-example@sha256:3da08ec52f1b40342876af299954372b9c002e3ce0a85560cf6cf5479fc0e9df","imagePullPolicy":"IfNotPresent","name":"springboot-example-sha256-1","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-07-13T06:00:58Z","lastUpdateTime":"2020-07-13T06:09:41Z","message":"ReplicaSet \"spring-boot-test-7c859b4897\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2020-07-13T06:09:46Z","lastUpdateTime":"2020-07-13T06:09:46Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":5,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2020-07-13T06:00:58Z"
  generation: 9
  labels:
    app: spring-boot-test
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: spring-boot-test
  namespace: default
  resourceVersion: "2671257"
  selfLink: /apis/apps/v1/namespaces/default/deployments/spring-boot-test
  uid: 1953c04e-003c-4e18-80a0-a7798d5d9e87
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-boot-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-test
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    spec:
      containers:
        - image: gcr.io/eternal-trainer-271923/springboot-example@sha256:3da08ec52f1b40342876af299954372b9c002e3ce0a85560cf6cf5479fc0e9df
          imagePullPolicy: IfNotPresent
          name: springboot-example-sha256-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2020-07-13T06:00:58Z"
      lastUpdateTime: "2020-07-13T06:21:07Z"
      message: ReplicaSet "spring-boot-test-657b676549" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-07-13T06:21:46Z"
      lastUpdateTime: "2020-07-13T06:21:46Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
