apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: springboot-example
  name: springboot-example-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/springboot-example-service
spec:
  clusterIP: 10.59.244.214
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31445
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: springboot-example
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.65.220.6
