apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"springboot-example","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy"},"name":"springboot-example","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"springboot-example"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"springboot-example","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy"}},"spec":{"containers":[{"image":"gcr.io/eternal-trainer-271923/github_jarkinv_springboot-swagger","imagePullPolicy":"IfNotPresent","name":"springboot-example-sha256-1"}]}}}}
  creationTimestamp: "2020-07-09T09:55:17Z"
  generation: 5
  labels:
    app: springboot-example
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: springboot-example
  namespace: default
  resourceVersion: "2518467"
  selfLink: /apis/apps/v1/namespaces/default/deployments/springboot-example
  uid: 1876869e-a2c3-437a-a732-5ac6840095ec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springboot-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-example
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    spec:
      containers:
        - image: gcr.io/eternal-trainer-271923/github_jarkinv_springboot-swagger
          imagePullPolicy: IfNotPresent
          name: springboot-example-sha256-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2020-07-09T09:56:24Z"
      lastUpdateTime: "2020-07-09T09:56:24Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-07-12T22:44:42Z"
      lastUpdateTime: "2020-07-12T22:44:42Z"
      message: ReplicaSet "springboot-example-588f4948df" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
